Discovering target: Default
Discovering tests from assembly: C:\projects\AuthnSpike\AuthSpike.Specs\bin\Debug\AuthSpike.Specs.dll
Appdomain Disposed
Test Suite Dump
#0: AuthSpike.Specs/Default - 
#1: Default - 
#2: AuthSpike.Specs - 
#3: AuthenticationManager - 
#4: Authenticate valid credentials - TestAssembly:AuthSpike.Specs/Feature:AuthenticationManager/Scenario:Authenticate+valid+credentials
#5: Authenticate invalid credentials - TestAssembly:AuthSpike.Specs/Feature:AuthenticationManager/Scenario:Authenticate+invalid+credentials
End: Test Suite Dump
Thread#0:Scheduler: get next test for thread
Thread#:Scheduler: testitem #4 from normal test queue 
Thread#0:Scheduler: considering testitem #4 for thread
Thread#0:Scheduler: using testitem #4 for thread
Thread#0:Scheduler: Test #4 is scheduled for thread
Thread#0:Scheduler: with testItemExecutionIndex 0
Thread #0: creating new test thread executor for AuthSpike.Specs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (target: Default)
Loading SpecRun type 'TechTalk.SpecRun.Framework.TestAssemblyExecutor' from: C:\Users\Rick\AppData\Local\Temp\VisualStudioTestExplorerExtensions\SpecRun.Runner.1.5.2\tools\TechTalk.SpecRun.Framework.Executor.dll
Thread#0: Test #4/0 is started on thread #0
Thread#0:B:Given I have an instance of the authentication manager
Thread#0:T:done: AuthenticationManagerSteps.GivenIHaveAnInstanceOfTheAuthenticationManager() (0.0s)
Thread#0:B:When I call authenticate with these credentials
Thread#0:B:  --- table step argument ---
Thread#0:B:  | Field    | Value    |
Thread#0:B:  | Username | username |
Thread#0:B:  | Password | password |
Thread#0:T:done: AuthenticationManagerSteps.WhenICallAuthenticateWithTheseCredentials(<table>) (0.0s)
Thread#0:B:Then I should receive a token
Thread#0:T:done: AuthenticationManagerSteps.ThenIShouldReceiveAToken() (0.0s)
Thread#0:B:And an exception should not be thrown
Thread#0:T:done: AuthenticationManagerSteps.ThenAnExceptionShouldNotBeThrown() (0.0s)
Thread#0:Scheduler: get next test for thread
Thread#:Scheduler: testitem #5 from normal test queue 
Thread#0:Scheduler: considering testitem #5 for thread
Thread#0:Scheduler: using testitem #5 for thread
Thread#0:Scheduler: Test #5 is scheduled for thread
Thread#0:Scheduler: with testItemExecutionIndex 0
Thread#0: Test #4/0 is finished on thread #0 as Succeeded within 0.1676254 seconds
Thread#0: Test #5/0 is started on thread #0
Thread#0:B:Given I have an instance of the authentication manager
Thread#0:T:done: AuthenticationManagerSteps.GivenIHaveAnInstanceOfTheAuthenticationManager() (0.0s)
Thread#0:B:When I call authenticate with these credentials
Thread#0:B:  --- table step argument ---
Thread#0:B:  | Field    | Value   |
Thread#0:B:  | Username | baduser |
Thread#0:B:  | Password | badpass |
Thread#0:T:done: AuthenticationManagerSteps.WhenICallAuthenticateWithTheseCredentials(<table>) (0.0s)
Thread#0:B:Then An exception should be thrown
Thread#0:T:done: AuthenticationManagerSteps.ThenAnExceptionShouldBeThrown() (0.0s)
Thread#0:B:But I should not receive a token
Thread#0:T:error: The given key was not present in the dictionary.
Thread#0:Scheduler: reschedule tests for testitem #0
Thread#0:Scheduler: get next test for thread
Thread#:Scheduler: dequeuing a rescheduled testitem: #5
Thread#0:Scheduler: considering testitem #5 for thread
Thread#0:Scheduler: using testitem #5 for thread
Thread#0:Scheduler: Test #5 is scheduled for thread
Thread#0:Scheduler: with testItemExecutionIndex 0
Thread#0: Test #5/0 is finished on thread #0 as Failed within 0.0160148 seconds
Thread#0: Test #5/1 is started on thread #0
Thread#0:B:Given I have an instance of the authentication manager
Thread#0:T:done: AuthenticationManagerSteps.GivenIHaveAnInstanceOfTheAuthenticationManager() (0.0s)
Thread#0:B:When I call authenticate with these credentials
Thread#0:B:  --- table step argument ---
Thread#0:B:  | Field    | Value   |
Thread#0:B:  | Username | baduser |
Thread#0:B:  | Password | badpass |
Thread#0:T:done: AuthenticationManagerSteps.WhenICallAuthenticateWithTheseCredentials(<table>) (0.0s)
Thread#0:B:Then An exception should be thrown
Thread#0:T:done: AuthenticationManagerSteps.ThenAnExceptionShouldBeThrown() (0.0s)
Thread#0:B:But I should not receive a token
Thread#0:T:error: The given key was not present in the dictionary.
Thread#0:Scheduler: get next test for thread
Thread#:Scheduler: dequeuing a rescheduled testitem: #5
Thread#0:Scheduler: considering testitem #5 for thread
Thread#0:Scheduler: using testitem #5 for thread
Thread#0:Scheduler: Test #5 is scheduled for thread
Thread#0:Scheduler: with testItemExecutionIndex 0
Thread#0: Test #5/1 is finished on thread #0 as Failed within 0.0060043 seconds
Thread#0: Test #5/2 is started on thread #0
Thread#0:B:Given I have an instance of the authentication manager
Thread#0:T:done: AuthenticationManagerSteps.GivenIHaveAnInstanceOfTheAuthenticationManager() (0.0s)
Thread#0:B:When I call authenticate with these credentials
Thread#0:B:  --- table step argument ---
Thread#0:B:  | Field    | Value   |
Thread#0:B:  | Username | baduser |
Thread#0:B:  | Password | badpass |
Thread#0:T:done: AuthenticationManagerSteps.WhenICallAuthenticateWithTheseCredentials(<table>) (0.0s)
Thread#0:B:Then An exception should be thrown
Thread#0:T:done: AuthenticationManagerSteps.ThenAnExceptionShouldBeThrown() (0.0s)
Thread#0:B:But I should not receive a token
Thread#0:T:error: The given key was not present in the dictionary.
Thread#0:Scheduler: get next test for thread
Thread#:Scheduler: at the end of normal test queue
Thread#0:Scheduler: enumerator for thread is at end
Thread#0:Scheduler: No more tests for thread 
Thread#0: Test #5/2 is finished on thread #0 as Failed within 0.0070045 seconds
Appdomain Disposed
Thread#-1:Scheduler: get next test for thread
Thread#:Scheduler: at the end of normal test queue
Thread#-1:Scheduler: enumerator for thread is at end
Total: 2 (test executions: 4)
Succeeded: 1
Ignored: 0
Pending: 0
Skipped: 0
Failed: 1
